from app import app
from models import db
from models import User, Task


def setup_module():
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
    app.config["SECRET_KEY"] = "test"
    app.config["JWT_SECRET_KEY"] = "jwt_test"

    with app.app_context():
        db.create_all()


def clear_db():
    with app.app_context():
        Task.query.delete()
        User.query.delete()
        db.session.commit()


def teardown_module():
    with app.app_context():
        db.drop_all()


def get_token(client):
    clear_db()

    client.post("/register", json={"username": "taskuser", "password": "pass123"})

    res = client.post("/login", json={"username": "taskuser", "password": "pass123"})

    return res.get_json()["access_token"]


def test_create_task():
    client = app.test_client()
    token = get_token(client)

    res = client.post(
        "/tasks",
        json={"title": "Test Task 1", "description": "Test Task"},
        headers={"Authorization": f"Bearer {token}"},
    )

    assert res.status_code == 200
    assert res.get_json()["message"] == "Task Created"


def test_get_task():
    client = app.test_client()
    token = get_token(client)

    client.post(
        "/tasks",
        json={"title": "Test Task 1", "description": "Test Task"},
        headers={"Authorization": f"Bearer {token}"},
    )
    res = client.get("/tasks", headers={"Authorization": f"Bearer {token}"})

    data = res.get_json()
    assert res.status_code == 200
    assert data["total"] == 1
    assert len(data["tasks"]) == 1


def test_get_task_by_id():
    client = app.test_client()
    token = get_token(client)

    client.post(
        "/tasks",
        json={"title": "Test Task 1", "description": "Test Task"},
        headers={"Authorization": f"Bearer {token}"},
    )

    # to get the autogenerated uuid
    tasks_response = client.get(
        "/tasks",
        json={"title": "Test Task 1", "description": "Test Task"},
        headers={"Authorization": f"Bearer {token}"},
    ).get_json()

    task_id = tasks_response["tasks"][0]["id"]

    res = client.get(f"/tasks/{task_id}", headers={"Authorization": f"Bearer {token}"})

    assert res.status_code == 200
    assert res.get_json()["id"] == task_id


def test_update_task():
    client = app.test_client()
    token = get_token(client)

    client.post(
        "/tasks",
        json={"title": "Old", "description": "Test"},
        headers={"Authorization": f"Bearer {token}"},
    )

    task_id = client.get(
        "/tasks", headers={"Authorization": f"Bearer {token}"}
    ).get_json()["tasks"][0]["id"]

    res = client.put(
        f"/tasks/{task_id}",
        json={"completed": True},
        headers={"Authorization": f"Bearer {token}"},
    )

    assert res.status_code == 200


def test_delete_task():
    client = app.test_client()
    token = get_token(client)

    client.post(
        "/tasks",
        json={"title": "Delete", "description": "Test"},
        headers={"Authorization": f"Bearer {token}"},
    )

    task_id = client.get(
        "/tasks", headers={"Authorization": f"Bearer {token}"}
    ).get_json()["tasks"][0]["id"]

    res = client.delete(
        f"/tasks/{task_id}", headers={"Authorization": f"Bearer {token}"}
    )

    assert res.status_code == 200
    assert res.get_json()["message"] == "Task deleted"


def test_tasks_without_token():
    client = app.test_client()

    res = client.get("/tasks")
    assert res.status_code == 401


def test_filter_completed_tasks():
    clear_db()
    client = app.test_client()
    token = get_token(client)

    # create mixed tasks
    client.post(
        "/tasks",
        json={"title": "Task 1", "description": "A"},
        headers={"Authorization": f"Bearer {token}"}
    )

    client.post(
        "/tasks",
        json={"title": "Task 2", "description": "B"},
        headers={"Authorization": f"Bearer {token}"}
    )

    # mark one as completed
    task_id = client.get(
        "/tasks",
        headers={"Authorization": f"Bearer {token}"}
    ).get_json()["tasks"][0]["id"]

    client.put(
        f"/tasks/{task_id}",
        json={"completed": True},
        headers={"Authorization": f"Bearer {token}"}
    )

    # filter completed
    res = client.get(
        "/tasks?completed=true",
        headers={"Authorization": f"Bearer {token}"}
    )

    data = res.get_json()

    assert res.status_code == 200
    assert data["total"] == 1
    assert data["tasks"][0]["completed"] is True


def test_filter_pending_task():
    clear_db()

    client = app.test_client()
    token = get_token(client)

    # create mixed tasks
    client.post(
        "/tasks",
        json={"title": "Task 1", "description": "A"},
        headers={"Authorization": f"Bearer {token}"}
    )

    res = client.get(
            "/tasks?completed=false",
            headers={"Authorization": f"Bearer {token}"}
    )
    data = res.get_json()

    assert res.status_code == 200
    assert data["total"] == 1 
    assert data["tasks"][0]["completed"] == False


def test_tasks_pagination():
    client = app.test_client()
    token = get_token(client)

    # create 5 tasks
    for i in range(5):
        client.post(
            "/tasks",
            json={"title": f"Task {i}", "description": "Test"},
            headers={"Authorization": f"Bearer {token}"}
        )

    res = client.get(
        "/tasks?page=1&per_page=2",
        headers={"Authorization": f"Bearer {token}"}
    )

    data = res.get_json()

    assert res.status_code == 200
    assert len(data["tasks"]) == 2
    assert data["total"] == 5
